installed libgl1-mesa-dri from the debian jessie/testing distribution because mesa 9.2 holds/suports the newest Intel 5000 sereis GPU drivers

diff --git a/var/lib/dpkg/info/libc6:i386.postinst b/var/lib/dpkg/info/libc6:i386.postinst
--- a/var/lib/dpkg/info/libc6:i386.postinst
+++ b/var/lib/dpkg/info/libc6:i386.postinst
@@ -116,8 +116,8 @@ then
     all_upgraded=yes
     if [ -n "$hwcappkgs" ]; then
         for pkg in $hwcappkgs ; do
-            ver=$(dpkg-query -l $pkg 2>/dev/null | sed -e '/^[a-z][a-z]\s/!d;/^.[nc]/d;' -e "s/^..\s\+$pkg\s\+//;s/\s.*//g")
-            if [ -n "$ver" ] && [ "$ver" != "2.13-38" ]; then
+            ver=$(dpkg-query -l $pkg 2>/dev/null | sed -e '/^[a-z][a-z]\s/!d;/^.[nc]/d;' -e "s/^..\s\+$pkg[0-9a-z:]*\s\+//;s/\s.*//g")
+            if [ -n "$ver" ] && [ "$ver" != "2.17-97" ]; then
                 all_upgraded=no
             fi
         done
@@ -139,7 +139,7 @@ then
 	if [ ! -d /var/mail ] && [ ! -L /var/mail ]; then
 	    ln -sf spool/mail /var/mail
 	fi
-	if dpkg --compare-versions "$preversion" lt 2.13; then
+	if dpkg --compare-versions "$preversion" lt 2.17; then
 	    check="apache2.2-common apache apache-ssl apache-perl autofs at"
 	    check="$check boa cucipop courier-authdaemon cron cups exim"
 	    check="$check exim4-base dovecot-common cucipop incron lprng lpr"
@@ -299,12 +299,28 @@ then
 	    else
 		echo "Nothing to restart."
 	    fi
-	fi # end upgrading and $preversion lt 2.13
+	fi # end upgrading and $preversion lt 2.17
     fi # Upgrading
 
-    # Restart init. If it fails, there is nothing we can do, so 
-    # just ignore the error
-    telinit u 2> /dev/null || true ; sleep 1
+    # Restart init.  Currently handles chroots and upstart, and assumes
+    # anything else is going to not fail at behaving like sysvinit:
+    TELINIT=yes
+    if ischroot 2>/dev/null; then
+        # Don't bother trying to re-exec init from a chroot:
+        TELINIT=no
+    else
+        if [ -x "`which initctl`" ]; then
+            UPSTART=$(initctl version 2>/dev/null | awk '/upstart/ {print $3}' | tr -d ')')
+            if dpkg --compare-versions "$UPSTART" lt-nl 1.6.1; then
+                # This is an old upstart that can't re-exec statefully:
+                TELINIT=no
+                touch /var/run/init.upgraded
+            fi
+        fi
+    fi
+    if [ "$TELINIT" = "yes" ]; then
+        telinit u 2>/dev/null || true ; sleep 1
+    fi
 fi
 
 # Automatically added by dh_makeshlibs
